name: 'publish_dev'

on:
  workflow_dispatch:

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target universal-apple-darwin'
          - platform: 'windows-latest'
            args: '-c src-tauri/prerelease.conf.json'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install frontend dependencies
        run: npm install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'v__VERSION__'
          releaseBody: | 
            ## Roadmap/Features (implemented checked)
            - [x] {insert changes here...}
            
            _ℹ️ As a pre-release, this version of Task Manager does not have all features we intend to put in this release implemented, and those that are are likely buggy._
            
            ## Installation Instructions and Notes
            Since our app is so new, both macOS and Windows erroneously flag Task Manager as malware. **So long as you download an official release, the installer is malware-free**. However, you may have to take the measures outlined in the instructions below to assuage your computer's fears.

            ### Windows
            1. Download the file ending in `.msi` below (your browser may also make it difficult to download)
            5. SmartScreen may prevent the installer from running. If it does, just click "More Info" and then select "Run Anyway"
            6. Proceed through the installation process

            ### macOS
            1. Download the `.dmg` file
            2. Open it once downloaded and drag and drop Task Manager onto the Applications folder. **Do not close the window yet!**
            3. Double click Applications
            8. Right click on Task Manager and select "Open"
            9. Select "Open" again
          releaseDraft: true
          prerelease: true
          args: ${{ matrix.args }}
